---
- name: Install Kazoo
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
   - kazoo-applications
   - kazoo-application-*
  notify: Restart Kazoo

- name: Create Kazoo config.ini
  template:
    src: config.ini.j2
    dest: /etc/kazoo/core/config.ini
  notify: Restart Kazoo

- name: Create Kazoo vm.args
  template:
    src: vm.args.j2
    dest: /etc/kazoo/core/vm.args
  notify: Restart Kazoo

- name: Start and Enable Kazoo Applications
  service:
    name: kazoo-applications
    state: started
    enabled: yes

- name: Start and Enable ecallmgr
  service:
    name: kazoo-ecallmgr
    state: started
    enabled: yes
 
- name: Wait for Database Initialization
  waitdbinit:

- name: Cluster Freeswitch
  freeswithcluster:
    erlang_cookie: "{{ erlang_cookie }}"
    freeswitch_hosts: "{{ groups['freeswitch'] | map('extract', hostvars, ['ansible_fqdn']) | join(',') }}"

- name: Cluster Kamailio
  kamailiocluster:
    erlang_cookie: "{{ erlang_cookie }}"
    kamailio_ips: "{{ groups['kamailio'] | map('extract', hostvars, ['public_ipv4']) | join(',') }}"

